languageCode = "en-us"
title = "NeoSki"
enableRobotsTXT = "true"
baseURL = "https://neoski.tk/"
[taxonomies]
  tag = 'tags'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true